#nullable enable
using GregTechCEuTerraria.Api.Recipe;

namespace GregTechCEuTerraria.Common.Recipe;

public static class GTRecipeTypes
{
	public static readonly GTRecipeType MACERATOR                 = GTRecipeType.GetOrCreate("macerator");
	public static readonly GTRecipeType ALLOY_SMELTER             = GTRecipeType.GetOrCreate("alloy_smelter");
	public static readonly GTRecipeType ASSEMBLER                 = GTRecipeType.GetOrCreate("assembler");
	public static readonly GTRecipeType ASSEMBLY_LINE             = GTRecipeType.GetOrCreate("assembly_line");
	public static readonly GTRecipeType AUTOCLAVE                 = GTRecipeType.GetOrCreate("autoclave");
	public static readonly GTRecipeType BENDER                    = GTRecipeType.GetOrCreate("bender");
	public static readonly GTRecipeType BREWERY                   = GTRecipeType.GetOrCreate("brewery");
	public static readonly GTRecipeType CANNER                    = GTRecipeType.GetOrCreate("canner");
	public static readonly GTRecipeType CHEMICAL_BATH             = GTRecipeType.GetOrCreate("chemical_bath");
	public static readonly GTRecipeType CENTRIFUGE                = GTRecipeType.GetOrCreate("centrifuge");
	public static readonly GTRecipeType CHEMICAL_REACTOR          = GTRecipeType.GetOrCreate("chemical_reactor");
	public static readonly GTRecipeType CIRCUIT_ASSEMBLER         = GTRecipeType.GetOrCreate("circuit_assembler");
	public static readonly GTRecipeType COMPRESSOR                = GTRecipeType.GetOrCreate("compressor");
	public static readonly GTRecipeType DISTILLERY                = GTRecipeType.GetOrCreate("distillery");
	public static readonly GTRecipeType DISTILLATION_TOWER        = GTRecipeType.GetOrCreate("distillation_tower");
	public static readonly GTRecipeType ELECTROLYZER              = GTRecipeType.GetOrCreate("electrolyzer");
	public static readonly GTRecipeType ELECTROMAGNETIC_SEPARATOR = GTRecipeType.GetOrCreate("electromagnetic_separator");
	public static readonly GTRecipeType EXTRACTOR                 = GTRecipeType.GetOrCreate("extractor");
	public static readonly GTRecipeType FERMENTER                 = GTRecipeType.GetOrCreate("fermenter");
	public static readonly GTRecipeType FLUID_HEATER              = GTRecipeType.GetOrCreate("fluid_heater");
	public static readonly GTRecipeType FLUID_SOLIDIFIER          = GTRecipeType.GetOrCreate("fluid_solidifier");
	public static readonly GTRecipeType FORGE_HAMMER              = GTRecipeType.GetOrCreate("forge_hammer");
	public static readonly GTRecipeType FORMING_PRESS             = GTRecipeType.GetOrCreate("forming_press");
	public static readonly GTRecipeType LATHE                     = GTRecipeType.GetOrCreate("lathe");
	public static readonly GTRecipeType MIXER                     = GTRecipeType.GetOrCreate("mixer");
	public static readonly GTRecipeType ORE_WASHER                = GTRecipeType.GetOrCreate("ore_washer");
	public static readonly GTRecipeType PACKER                    = GTRecipeType.GetOrCreate("packer");
	public static readonly GTRecipeType POLARIZER                 = GTRecipeType.GetOrCreate("polarizer");
	public static readonly GTRecipeType WIREMILL                  = GTRecipeType.GetOrCreate("wiremill");
	public static readonly GTRecipeType ELECTRIC_FURNACE          = GTRecipeType.GetOrCreate("electric_furnace");
	public static readonly GTRecipeType ARC_FURNACE               = GTRecipeType.GetOrCreate("arc_furnace");
	public static readonly GTRecipeType CUTTER                    = GTRecipeType.GetOrCreate("cutter");
	public static readonly GTRecipeType EXTRUDER                  = GTRecipeType.GetOrCreate("extruder");
	public static readonly GTRecipeType SCANNER                   = GTRecipeType.GetOrCreate("scanner");
	public static readonly GTRecipeType LASER_ENGRAVER            = GTRecipeType.GetOrCreate("laser_engraver");
	public static readonly GTRecipeType SIFTER                    = GTRecipeType.GetOrCreate("sifter");
	public static readonly GTRecipeType THERMAL_CENTRIFUGE        = GTRecipeType.GetOrCreate("thermal_centrifuge");
	public static readonly GTRecipeType GAS_COLLECTOR             = GTRecipeType.GetOrCreate("gas_collector");
	public static readonly GTRecipeType AIR_SCRUBBER              = GTRecipeType.GetOrCreate("air_scrubber");
	public static readonly GTRecipeType ROCK_BREAKER             = GTRecipeType.GetOrCreate("rock_breaker");
	public static readonly GTRecipeType STEAM_BOILER              = GTRecipeType.GetOrCreate("steam_boiler");
	public static readonly GTRecipeType COKE_OVEN                 = GTRecipeType.GetOrCreate("coke_oven");
	public static readonly GTRecipeType PRIMITIVE_BLAST_FURNACE   = GTRecipeType.GetOrCreate("primitive_blast_furnace");
	public static readonly GTRecipeType LARGE_BOILER              = GTRecipeType.GetOrCreate("large_boiler");
	public static readonly GTRecipeType STEAM_TURBINE             = GTRecipeType.GetOrCreate("steam_turbine");
	public static readonly GTRecipeType GAS_TURBINE               = GTRecipeType.GetOrCreate("gas_turbine");
	public static readonly GTRecipeType COMBUSTION                = GTRecipeType.GetOrCreate("combustion_generator");
	public static readonly GTRecipeType PLASMA_GENERATOR          = GTRecipeType.GetOrCreate("plasma_generator");
	public static readonly GTRecipeType DUMMY                     = GTRecipeType.GetOrCreate("dummy");
	public static readonly GTRecipeType LARGE_MINER               = GTRecipeType.GetOrCreate("large_miner");
	public static readonly GTRecipeType FLUID_DRILLING_RIG        = GTRecipeType.GetOrCreate("fluid_drilling_rig");
	public static readonly GTRecipeType PRIMITIVE_PUMP            = GTRecipeType.GetOrCreate("primitive_pump");
	public static readonly GTRecipeType MULTIBLOCK_STRUCTURE      = GTRecipeType.GetOrCreate("multiblock_structure");
	public static readonly GTRecipeType FUSION_REACTOR            = GTRecipeType.GetOrCreate("fusion_reactor");
	public static readonly GTRecipeType RESEARCH_STATION          = GTRecipeType.GetOrCreate("research_station");
	public static readonly GTRecipeType BLAST_RECIPES             = GTRecipeType.GetOrCreate("electric_blast_furnace");
	public static readonly GTRecipeType LARGE_CHEMICAL_RECIPES    = GTRecipeType.GetOrCreate("large_chemical_reactor");
	public static readonly GTRecipeType VACUUM_RECIPES            = GTRecipeType.GetOrCreate("vacuum_freezer");
	public static readonly GTRecipeType IMPLOSION_RECIPES         = GTRecipeType.GetOrCreate("implosion_compressor");
	public static readonly GTRecipeType ALLOY_BLAST_RECIPES       = GTRecipeType.GetOrCreate("alloy_blast_smelter");
	public static readonly GTRecipeType PYROLYSE_RECIPES          = GTRecipeType.GetOrCreate("pyrolyse_oven");
	public static readonly GTRecipeType CRACKING_RECIPES          = GTRecipeType.GetOrCreate("cracker");
}
